ALTER TABLE IF EXIST accounts DROP CONSTRAINT IF EXISTS "owner_currency_key";
ALTER TABLE IF EXIST accounts DROP CONSTRAINT IF EXISTS "account_owner_fkey";
ALTER TABLE IF EXIST accounts DROP CONSTRAINT IF EXISTS "owner_currency_fkey";

DROP TABLE IF EXISTS users;